-- AlterTable
ALTER TABLE "HostingPlan" ADD COLUMN     "addonDomains" TEXT NOT NULL DEFAULT 'TODO_CONFIRM',
ADD COLUMN     "freeDomain" TEXT NOT NULL DEFAULT 'TODO_CONFIRM',
ADD COLUMN     "freeSsl" TEXT NOT NULL DEFAULT 'TODO_CONFIRM',
ADD COLUMN     "subdomains" TEXT NOT NULL DEFAULT 'TODO_CONFIRM';
